### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by thehybridtechnician** [Wolfenswan/Unnamed-Roguelike#1]
@Wolfenswan - Have to say I am very impressed with your project.  I have been playing with roguelikes and the Python TCOD library with my 13 year old son and keep checking your code to see how you have been solving some of the more interesting problems.
Would it be alright if I forked your project to use as a starting point for a roguelike?  How would you like to attribute back to you?  What license does your project fall under?

Thank you very much.

**Comment by Wolfenswan** [comment]
Hey @thehybridtechnician , I'm glad the project is able to be of help! Fork as you please, I have not really considered any license and simply added the GNU V3 now.

Unfortunately I haven't been able to actively develop for a while, due to other commitments but what exists *should* all be working. Keep in mind that I treat it more as a coding playground than a disciplined project and I have neither a background in CS nor in Game Dev, so some of my solutions might be... less than ideal.

That said, as a starting point I'd strongly suggest the tutorial that is linked in the readme. All of what I've done did grow from that base. Furthermore the roguelikedev-subreddit, as well as the coupled discord channels are incredbly friendly and helpful communities, both in terms of general development and specifically the tutorial.

**Comment by thehybridtechnician** [comment]
Thank you very much.  I have gone through all of the tutorial.  It is the next steps around window and rendering that is pretty cool.  Again, thank you!
